"""adding clients table

Revision ID: 15ebf837513f
Revises: 
Create Date: 2021-10-31 12:01:25.741763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ebf837513f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_name', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('client_email', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_email'), 'clients', ['client_email'], unique=True)
    op.create_index(op.f('ix_clients_company'), 'clients', ['company'], unique=False)
    op.create_index(op.f('ix_clients_contact_name'), 'clients', ['contact_name'], unique=False)
    op.create_index(op.f('ix_clients_login_name'), 'clients', ['login_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_login_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_contact_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_company'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
