"""adding orders model

Revision ID: 6b4b7af87734
Revises: c4c39886d1cc
Create Date: 2021-10-31 13:12:28.160215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4b7af87734'
down_revision = 'c4c39886d1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('clientid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('order_number')
    )
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
