"""adding vehicles model

Revision ID: 913d8959a5b9
Revises: 6b4b7af87734
Create Date: 2021-10-31 13:36:22.622873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913d8959a5b9'
down_revision = '6b4b7af87734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_vehicle'), 'vehicles', ['vehicle'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vehicle'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
