"""adding foreign key to orders model

Revision ID: c4aad91f5131
Revises: 913d8959a5b9
Create Date: 2021-10-31 13:37:39.639384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4aad91f5131'
down_revision = '913d8959a5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('vehicleid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'vehicles', ['vehicleid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'vehicleid')
    # ### end Alembic commands ###
